/* Sofisticatto Financeiro V235 — Faturas Correios: API + parser seguro */
let correiosFaturaLinhas=[]; let correiosFaturaMeta={arquivo:'',importadoEm:null,fatura:''}; let correiosFaturasApi=[];
function cfTxt(v){return String(v??'').trim()} function cfNorm(v){return cfTxt(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()} function cfTrack(v){return cfTxt(v).toUpperCase().replace(/[^A-Z0-9]/g,'')} function cfCep(v){const d=cfTxt(v).replace(/\D/g,'');return d.length===8?`${d.slice(0,5)}-${d.slice(5)}`:cfTxt(v)} function cfNumBR(v){let s=cfTxt(v).replace(/R\$/gi,'').replace(/\s/g,'');if(!s)return 0;if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return Number(s)||0} function cfMoeda(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})} function cfEsc(v){return cfTxt(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))} function cfCsvCell(v){const s=cfTxt(v);return /[;"\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s} function cfDetectSep(line){return (line.match(/;/g)||[]).length >= (line.match(/,/g)||[]).length?';':','} function cfParseLine(line,sep){let a=[],cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===sep&&!q){a.push(cur);cur=''}else cur+=c}a.push(cur);return a} function cfKey(k){return cfNorm(k).replace(/[^a-z0-9]/g,'')} function cfPick(o,names){for(const n of names){const k=Object.keys(o).find(x=>cfKey(x)===cfKey(n));if(k&&cfTxt(o[k]))return o[k]}return ''}
function cfTrackValido(v){return /^[A-Z]{2}\d{9}BR$/.test(cfTrack(v))}
function cfParseCsv(text){
 const raw=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/); let hi=raw.findIndex(l=>/ETIQUETA/i.test(l)&&/CEP\s*DESTINATARIO|CEP/i.test(l)&&/SERVICO/i.test(l)); if(hi<0)return [];
 const sep=cfDetectSep(raw[hi]),headers=cfParseLine(raw[hi],sep).map(x=>x.trim()),out=[];
 for(let i=hi+1;i<raw.length;i++){const line=raw[i].trim();if(!line)continue;if(/^TOTALIZACAO\s+POR\s+SERVICO|^TOTALIZAÇÃO\s+POR\s+SERVIÇO|^TOTALIZACAO\s+FATURA|^TOTALIZAÇÃO\s+FATURA/i.test(cfNorm(line).toUpperCase()))break;const vals=cfParseLine(raw[i],sep),o={};headers.forEach((h,j)=>o[h]=vals[j]??'');const tr=cfPick(o,['ETIQUETA','OBJETO','RASTREIO','CODIGO RASTREAMENTO']);if(cfTrackValido(tr))out.push(o)} return out;
}
async function cfCarregarBase(){let rast=[],col=[];try{const r=await banco.from('logistica_rastreamentos').select('*').eq('sentido','saida');if(!r.error)rast=r.data||[]}catch(e){}try{const r=await banco.from('coleta_agendamentos').select('*').order('created_at',{ascending:false}).limit(3000);if(!r.error)col=r.data||[]}catch(e){}return {rast,col}}
function cfInfoColeta(a){const d=a?.dados||{};return {cliente:a?.cliente_nome||d.razao_destino||'',nf:a?.numero_nf||d.numero_nf||d.numero_nfe||'',cidade:d.cidade_destino||'',uf:d.uf_destino||d.estado_destino||'',cep:d.cep_destino||'',pedido:d.numero_pedido||d.pedido||''}}
function cfAchar(row,base){const tr=cfTrack(row.rastreio);const r=base.rast.find(x=>cfTrack(x.protocolo_rastreio)===tr);if(r){const a=base.col.find(x=>String(x.id)===String(r.coleta_agendamento_id));const ci=cfInfoColeta(a);return {cliente:r.parceiro_nome||ci.cliente,nf:r.numero_nfe||ci.nf,pedido:ci.pedido,cidade:ci.cidade,uf:ci.uf,fonte:'Rastreio do portal',status:'ok'}}const a=base.col.find(x=>{const d=x.dados||{};return [x.codigo_coleta,x.protocolo_cotacao,d.codigo_rastreio,d.rastreio,d.objeto,d.etiqueta].some(v=>cfTrack(v)===tr)});if(a){const ci=cfInfoColeta(a);return {...ci,fonte:'Coleta do portal',status:'ok'}}return {cliente:'',nf:'',pedido:'',cidade:'',uf:'',fonte:'Não identificado',status:'pendente'}}
async function cfProcessarTexto(txt,nome='Extrato Correios',fatura=''){const dados=cfParseCsv(txt);if(!dados.length)throw new Error('Não encontrei postagens válidas no extrato. A V235 aceita somente linhas com etiqueta padrão XX999999999BR e ignora as totalizações.');const base=await cfCarregarBase();correiosFaturaLinhas=dados.map(o=>{const row={data:cfPick(o,['DATA POSTAGEM','DATA','DATA DA POSTAGEM']),servico:cfPick(o,['SERVICO','SERVIÇO','NOME SERVICO']),cep:cfCep(cfPick(o,['CEP DESTINATARIO','CEP DESTINATÁRIO','CEP'])),rastreio:cfTrack(cfPick(o,['ETIQUETA','OBJETO','RASTREIO'])),peso:cfPick(o,['PESO','PESO (G)','PESO G']),valor:cfNumBR(cfPick(o,['VALOR LIQUIDO','VALOR LÍQUIDO','VALOR UNITARIO','VALOR UNITÁRIO','VALOR'])),declarado:cfNumBR(cfPick(o,['VALOR DECLARADO','DECLARADO']))};return {...row,...cfAchar(row,base)}});correiosFaturaMeta={arquivo:nome,importadoEm:new Date().toISOString(),fatura};cfRender()}
async function importarFaturaCorreiosCsv(){const file=document.getElementById('corFaturaCsv')?.files?.[0];if(!file)return alert('Selecione o CSV dos Correios.');try{await cfProcessarTexto(await file.text(),file.name)}catch(e){alert(e.message)}}
function cfAdmin(){return sessionStorage.getItem('integrations_admin_key')||localStorage.getItem('integrations_admin_key')||''}
async function cfApi(subaction,{method='GET',query={},body}={}){const k=cfAdmin();if(!k)throw new Error('Valide primeiro a chave administrativa das integrações.');const q=new URLSearchParams({action:'faturas-correios',subaction,...query});const r=await fetch('/api/integracoes?'+q,{method,headers:{'x-integrations-admin-key':k,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(j.erro||`HTTP ${r.status}`);return j}
function cfDataBR(v){if(!v)return '';const [a,m,d]=v.split('-');return `${d}-${m}-${a}`}
async function consultarFaturasCorreiosApi(){const out=document.getElementById('corFaturasApiStatus');try{out.textContent='Consultando faturas diretamente nos Correios...';const ini=document.getElementById('corFatDataIni').value,fim=document.getElementById('corFatDataFim').value;if(!ini||!fim)throw new Error('Informe o período inicial e final.');const j=await cfApi('listar',{query:{dataInicial:cfDataBR(ini),dataFinal:cfDataBR(fim)}});correiosFaturasApi=j.faturas||[];cfRenderFaturasApi();out.textContent=`${correiosFaturasApi.length} fatura(s) encontrada(s) no contrato.`}catch(e){out.textContent='❌ '+e.message}}
function cfRenderFaturasApi(){const box=document.getElementById('corFaturasApiLista');if(!box)return;box.innerHTML=correiosFaturasApi.length?correiosFaturasApi.map((f,i)=>`<div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr auto;gap:8px;align-items:center;padding:9px;border-bottom:1px solid #e3e0f2"><b>Fatura ${cfEsc(f.id||f.fatura||'')}</b><span>${cfEsc(f.status||'')}</span><span>Venc.: ${cfEsc(f.vencimento||'—')}</span><span><b>${cfMoeda(f.valor)}</b></span><button class="btn azul" onclick="baixarAnaliticoFaturaCorreios(${i})">📊 Gerar relatório</button></div>`).join(''):'<div style="padding:10px">Nenhuma fatura no período.</div>'}
async function baixarAnaliticoFaturaCorreios(i){const f=correiosFaturasApi[i],out=document.getElementById('corFaturasApiStatus');if(!f)return;try{const num=f.id||f.fatura;out.textContent=`Solicitando extrato analítico da fatura ${num}...`;const s=await cfApi('solicitar-analitico',{method:'POST',body:{fatura:num,tipoDocumento:f.tipoDocumento||'RE',itemFatura:f.itemFatura||'001',drFatura:f.drFatura||f.dr}});const id=s.processamento?.id;if(!id)throw new Error('Os Correios não retornaram o ID do processamento.');let st=null;for(let n=0;n<12;n++){await new Promise(r=>setTimeout(r,n?1500:700));const z=await cfApi('status',{query:{id}});st=z.processamento;out.textContent=`Extrato ${num}: ${st?.status||'PROCESSANDO'}...`;if(String(st?.status||'').toUpperCase()==='SUCESSO')break;if(/ERRO|FALHA|CANCEL/i.test(String(st?.status||'')))throw new Error('Os Correios não conseguiram gerar o extrato: '+(st?.mensagem||st?.status))}if(String(st?.status||'').toUpperCase()!=='SUCESSO')throw new Error('O extrato ainda está sendo processado. Clique novamente em Gerar relatório em alguns instantes.');const arq=await cfApi('arquivo',{query:{id}});await cfProcessarTexto(arq.conteudo,arq.nome||`Fatura_${num}.csv`,String(num));out.textContent=`✅ Fatura ${num} carregada diretamente dos Correios: ${correiosFaturaLinhas.length} postagem(ns).`}catch(e){out.textContent='❌ '+e.message}}
function cfRender(){const tb=document.getElementById('corFaturaTabela'),res=document.getElementById('corFaturaResumo'),pend=document.getElementById('corFaturaPendencias');if(!tb)return;const total=correiosFaturaLinhas.reduce((s,x)=>s+x.valor,0),pac=correiosFaturaLinhas.filter(x=>/pac/i.test(x.servico)).length,sedex=correiosFaturaLinhas.filter(x=>/sedex/i.test(x.servico)).length,ok=correiosFaturaLinhas.filter(x=>x.status==='ok').length;res.innerHTML=`<div style="display:flex;gap:8px;flex-wrap:wrap"><span class="cf-kpi"><b>${correiosFaturaLinhas.length}</b> Postagens</span><span class="cf-kpi"><b>${pac}</b> PAC</span><span class="cf-kpi"><b>${sedex}</b> SEDEX</span><span class="cf-kpi"><b>${ok}</b> Identificados</span><span class="cf-kpi"><b>${cfMoeda(total)}</b> Total</span></div>`;tb.innerHTML=correiosFaturaLinhas.map((x,i)=>`<tr><td>${cfEsc(x.data)}</td><td><input value="${cfEsc(x.cliente)}" placeholder="Não identificado" oninput="cfEditar(${i},'cliente',this.value)"></td><td>${cfEsc([x.cidade,x.uf].filter(Boolean).join('/'))}</td><td><input value="${cfEsc(x.nf||x.pedido)}" placeholder="—" oninput="cfEditar(${i},'nf',this.value)"></td><td>${cfEsc(x.servico)}</td><td><b>${cfEsc(x.rastreio)}</b></td><td>${cfEsc(x.cep)}</td><td>${cfEsc(x.peso)}</td><td><b>${cfMoeda(x.valor)}</b></td><td>${x.status==='ok'?'✅':'❌'}</td></tr>`).join('');const n=correiosFaturaLinhas.filter(x=>x.status==='pendente').length;pend.innerHTML=n?`⚠️ <b>${n}</b> postagem(ns) ainda sem cliente. O sistema não associa automaticamente somente pelo CEP.`:'✅ Todas as postagens foram relacionadas.'}
function cfEditar(i,k,v){if(correiosFaturaLinhas[i]){correiosFaturaLinhas[i][k]=v;if(k==='cliente'&&cfTxt(v)){correiosFaturaLinhas[i].status='manual';correiosFaturaLinhas[i].fonte='Manual'}}}
function cfRelatorioHtml(){const total=correiosFaturaLinhas.reduce((s,x)=>s+x.valor,0),rows=correiosFaturaLinhas.map(x=>`<tr><td>${cfEsc(x.data)}</td><td><b>${cfEsc(x.cliente||'NÃO IDENTIFICADO')}</b></td><td>${cfEsc([x.cidade,x.uf].filter(Boolean).join('/'))}</td><td>${cfEsc(x.nf||x.pedido||'—')}</td><td>${cfEsc(x.servico)}</td><td>${cfEsc(x.rastreio)}</td><td>${cfEsc(x.cep)}</td><td>${cfEsc(x.peso)}</td><td>${cfMoeda(x.valor)}</td></tr>`).join('');return `<!doctype html><html><head><meta charset="utf-8"><style>@page{size:A4 landscape;margin:10mm}body{font-family:Arial;color:#29264a}h1{color:#4f459c}table{width:100%;border-collapse:collapse;font-size:9px}th{background:#4f459c;color:#fff;padding:6px}td{padding:5px;border-bottom:1px solid #ddd}tr:nth-child(even){background:#f7f6fb}.top{display:flex;gap:20px;margin:10px 0 15px}.top b{font-size:18px;color:#4f459c}</style></head><body><h1>Sofisticatto Cosméticos — Relatório dos Correios</h1><div>Fatura: ${cfEsc(correiosFaturaMeta.fatura||'—')} • ${cfEsc(correiosFaturaMeta.arquivo)}</div><div class="top"><div><b>${correiosFaturaLinhas.length}</b><br>Postagens</div><div><b>${cfMoeda(total)}</b><br>Total</div></div><table><tr><th>Data</th><th>Cliente</th><th>Cidade/UF</th><th>NF/Pedido</th><th>Serviço</th><th>Rastreio</th><th>CEP</th><th>Peso</th><th>Frete</th></tr>${rows}</table><script>onload=()=>setTimeout(()=>print(),200)<\/script></body></html>`}
function imprimirRelatorioFaturaCorreios(){if(!correiosFaturaLinhas.length)return alert('Carregue uma fatura primeiro.');const w=window.open('','_blank');if(!w)return alert('Libere pop-ups.');w.document.write(cfRelatorioHtml());w.document.close()}
function exportarRelatorioFaturaCorreiosCsv(){if(!correiosFaturaLinhas.length)return alert('Carregue uma fatura primeiro.');const hs=['Data','Cliente','Cidade/UF','NF/Pedido','Serviço','Rastreio','CEP','Peso','Frete','Identificação'];const ls=[hs.join(';'),...correiosFaturaLinhas.map(x=>[x.data,x.cliente,[x.cidade,x.uf].filter(Boolean).join('/'),x.nf||x.pedido,x.servico,x.rastreio,x.cep,x.peso,x.valor.toFixed(2).replace('.',','),x.fonte].map(cfCsvCell).join(';'))];const b=new Blob(['\uFEFF'+ls.join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='Relatorio_Correios_Sofisticatto_Detalhado.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener('DOMContentLoaded',()=>{const f=new Date(),i=new Date();i.setDate(i.getDate()-60);const a=document.getElementById('corFatDataIni'),b=document.getElementById('corFatDataFim');if(a&&!a.value)a.value=i.toISOString().slice(0,10);if(b&&!b.value)b.value=f.toISOString().slice(0,10)})
